Layout/Tab:
  Enabled: false
Layout/IndentationWidth:
  Width: 1
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
