require:
  - rubocop-performance
  - rubocop-rspec

Layout/IndentationStyle:
  EnforcedStyle: tabs
Layout/IndentationWidth:
  Width: 1
Layout/LineLength:
  Max: 100
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

RSpec/NestedGroups:
  Max: 5
